Test pdf reader
lablueprint/skid-row-arts-alliance pull request #10
Opened 2023-02-03 06:57 UTC by andhuynh

- Implemented react-native-pdf to display a pdf reader to display zines pulled from the SRAA website
- Integrated slider using community library to control the scrolling of the PDF
- Added a button to jump to a certain page as a test button as a precursor to a future interactive table of contents
- Button also respectively changes the slider to respective position in the PDF
- Created zine cards with a button that leads to a details screen with the PDF reader
- Details screen has a back button going back to the card screen

2023-02-06 02:35 UTC, he-is-james commented on mobile/App.js
>    );
For some reason, you don't have the stack navigator here? Might have been an error from a merge commit

2023-02-06 02:36 UTC, he-is-james commented on mobile/Components/Zines.js
> +import * as React from 'react';
I would rename this file to be `ZineCard` instead to be more specific

2023-02-06 02:37 UTC, he-is-james commented on mobile/Screen/MapScreen.js
> +  // };
I would remove this since this example will never be used again

2023-02-06 02:37 UTC, he-is-james commented on mobile/Screen/MapScreen.js
> +      {/* <Button title="Test" onPress={test} /> */}
Remove comment

2023-02-06 02:37 UTC, he-is-james commented on mobile/Screen/MapScreen.js
>  // eslint-disable-next-line import/no-unresolved
Remove these comments

2023-02-06 02:38 UTC, he-is-james commented on mobile/Screen/MapScreen.js
> +// import { URL } from '@env';
Remove comment

2023-02-06 02:39 UTC, he-is-james commented on mobile/Screen/MapScreen.js
> +          console.log(`Number of pages: ${numberOfPages}`);
Remove `console.log` if unnecessary

2023-02-06 02:39 UTC, he-is-james commented on mobile/Screen/ZineDetailsScreen.js
> +
I think the `MapScreen` content should be moved here

2023-02-06 02:40 UTC, he-is-james commented on mobile/Screen/ZinesScreen.js
> +  StyleSheet, Text, View, ScrollView,
`Text` and `View` can be removed

2023-02-06 02:42 UTC, he-is-james requested changes
Everything looks really cool so far, excited to see what it will look when all put together!

Main issues are the extra folder `ios` and `MapScreen`/`ZineDetailsScreen`. Add `ios` to the `.gitignore` file and try to check the stack navigator from the `main` branch. Also remember to merge!

2023-02-08 06:46 UTC, closed without merging

2023-02-08 06:47 UTC, andhuynh commented
oops