Implement Art Filtering Functionality and Styling
lablueprint/skid-row-arts-alliance pull request #34
Opened 2023-05-12 08:55 UTC by zhangjuliet

2023-05-12 09:00 UTC, zhangjuliet commented on mobile/package-lock.json
Wait should this be deleted?

2023-05-21 21:06 UTC, siddharthnandy commented on mobile/Components/AppNavigator.js
> +import {
can u put these all on one line (unless the linter specifies otherwise)

2023-05-21 22:17 UTC, siddharthnandy requested changes

2023-05-21 22:17 UTC, siddharthnandy commented on mobile/Screen/GalleryScreen.js
> +        <TouchableOpacity onPress={() => navigation.navigate('Artwork Filter')}>
Currently, when you enable a filter, go back to the Gallery screen, and then go back to the filter screen, none of the pre-selected filters are saved. Maybe use props to make sure that filters that are selected before are kept?

2023-05-31 04:19 UTC, zhangjuliet commented on mobile/Components/AppNavigator.js
> +function MapIcon({ focused }) {
work on this later; low priority

2023-05-31 04:19 UTC, zhangjuliet commented on mobile/Components/AppNavigator.js
> +          tabBarIcon: MapIcon,
work on this later; low priority

2023-05-31 04:19 UTC, zhangjuliet commented on mobile/Screen/ArtworkFilterScreen.js
> +      <View style={styles.headingContainer}>
work on this later; low priority

2023-05-31 04:56 UTC, siddharthnandy approved these changes

2023-05-31 04:56 UTC, merged