Portal gallery zines
lablueprint/skid-row-arts-alliance pull request #37
Opened 2023-05-21 21:04 UTC by he-is-james

- adjusted Submission Detail Screen
- edit button allows admin to edit title and description of a Submission, cancel will not update and save will update the database
- submit only available if the submission is incomplete and will update the status and comments
- change will be similar to edit but only update status and comments

2023-05-22 00:21 UTC, siddharthnandy requested changes

2023-05-22 00:21 UTC, siddharthnandy commented on mobile/Screen/GalleryScreen.js
> +                  id={imageData.SubmissionId}
will be changed with convention change in submissionController

2023-05-22 00:21 UTC, siddharthnandy commented on website/src/Pages/GalleryPage/GalleryPage.jsx
> +    const response = await axios.get('http://localhost:4000/submissions/getsubmissions');
Maybe keep the URL in a .env file like how we work with requests on mobile?

2023-05-22 00:21 UTC, siddharthnandy commented on website/src/Pages/GalleryPage/SubmissionDetailsPage.jsx
> +    const response = await axios.patch(`http://localhost:4000/submissions/updatesubmission/${id}`, {
env URL?

2023-05-22 00:21 UTC, siddharthnandy commented on website/src/Pages/GalleryPage/SubmissionDetailsPage.jsx
> +    const artwork = await axios.get('http://localhost:4000/submissions/getartwork', { params: { id } });
env URL?

2023-05-22 00:21 UTC, siddharthnandy commented on website/src/Pages/GalleryPage/SubmissionDetailsPage.jsx
> +  }, [update]);
is re-retrieving the entire Submission anytime admin updates a good idea, or can we not just work with whatever they inputted when they updated the submission?

2023-05-22 00:21 UTC, siddharthnandy commented on website/src/Pages/GalleryPage/SubmissionDetailsPage.jsx
> +    const response = await axios.patch(`http://localhost:4000/submissions/updatesubmission/${id}`, {
env URL?

2023-05-22 00:21 UTC, siddharthnandy commented on website/src/Pages/GalleryPage/SubmissionDetailsPage.jsx
> +    const response = await axios.patch(`http://localhost:4000/submissions/updatesubmission/${id}`, {
env URL?

2023-05-22 00:21 UTC, siddharthnandy commented on website/src/Pages/ZinesPage/ZineCard.jsx
> +    await axios.delete(`http://localhost:4000/zine/delete/${id}`);
env URL?

2023-05-22 00:21 UTC, siddharthnandy commented on website/src/Pages/ZinesPage/ZinesPage.jsx
> +    const response = await axios.get('http://localhost:4000/zine/get');
env URL?

2023-05-25 04:38 UTC, he-is-james commented on website/src/Pages/GalleryPage/SubmissionDetailsPage.jsx
> +    const response = await axios.patch(`http://localhost:4000/submissions/updatesubmission/${id}`, {
clean up

2023-05-25 04:41 UTC, siddharthnandy approved these changes

2023-05-25 04:43 UTC, merged