Nonprofit Details Page
lablueprint/skid-row-arts-alliance pull request #58
Opened 2023-08-15 03:44 UTC by he-is-james

- allows admin to add, edit and delete nonprofit details displayed on the app
- thumbnails are required for each nonprofit
- allows users to keep in touch through different modes of contact

2023-08-16 07:16 UTC, siddharthnandy requested changes
looks mostly good, added some comments

2023-08-16 07:16 UTC, siddharthnandy commented on website/src/Pages/NonprofitsPage/NonprofitsPage.jsx
> +  const previewEventDetails = (nonprofitDetails) => {
function name

2023-08-17 06:48 UTC, he-is-james commented on website/src/Components/NavigationBar/NavigationBar.css
> +  width: 165px;
yea that'll be cleaned up by styling later

2023-08-18 06:52 UTC, siddharthnandy approved these changes

2023-08-18 17:55 UTC, merged